"""Static makeup and jewelry guidance for each color season's paid result.

Same spirit as app/palettes.py: curated color-theory reference data, not
derived from a user's photo and not generated by an LLM. Keyed by `Season`
alone — undertone/depth/clarity are computed at scan time but never
persisted (see app/vision/season_classifier.py), and Season already encodes
undertone+depth 1:1, so it's the only classification signal available by the
time a paid report is viewed.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from app.palettes import Swatch
from app.vision.season_classifier import Season

# Two fixed reference colors shared by every season — only which one(s) a
# season recommends varies, so these aren't duplicated per season.
GOLD_SWATCH = Swatch("Gold", "#D4AF37")
SILVER_SWATCH = Swatch("Silver", "#C0C0C0")

Metal = Literal["Gold", "Silver", "Both"]


@dataclass(frozen=True)
class MakeupGuidance:
    foundation_undertone: str
    foundation_tip: str
    lip_shades: tuple[Swatch, ...]
    blush_shades: tuple[Swatch, ...]


@dataclass(frozen=True)
class JewelryGuidance:
    metal: Metal
    tip: str


@dataclass(frozen=True)
class BeautyGuidance:
    makeup: MakeupGuidance
    jewelry: JewelryGuidance
    shopping_guidance: str


GUIDANCE_BY_SEASON: dict[Season, BeautyGuidance] = {
    "Spring": BeautyGuidance(
        makeup=MakeupGuidance(
            foundation_undertone="Warm, golden undertone",
            foundation_tip=(
                "Look for foundations labeled 'warm' or 'golden' or 'peach' — "
                "avoid pink or ashy-toned shades, which mute your natural warmth."
            ),
            lip_shades=(
                Swatch("Coral Pink", "#E8735A"),
                Swatch("Peach Rose", "#E89478"),
                Swatch("Warm Nude", "#C98A64"),
                Swatch("Watermelon", "#E8556B"),
            ),
            blush_shades=(
                Swatch("Peach Blush", "#F2A488"),
                Swatch("Coral Blush", "#E8836A"),
            ),
        ),
        jewelry=JewelryGuidance(
            metal="Gold",
            tip=(
                "Gold and warm brass tones make your complexion glow — "
                "silver can look flat against your warm undertone."
            ),
        ),
        shopping_guidance=(
            "Build your wardrobe foundation from warm neutrals like camel, ivory, "
            "and warm gray, then save your brightest clear warm colors — coral, "
            "golden yellow, warm turquoise — for pieces near your face."
        ),
    ),
    "Summer": BeautyGuidance(
        makeup=MakeupGuidance(
            foundation_undertone="Cool, rosy undertone",
            foundation_tip=(
                "Look for foundations labeled 'cool' or 'neutral-cool' — avoid "
                "orange-leaning or deep golden shades, which can clash."
            ),
            lip_shades=(
                Swatch("Soft Rose", "#C77B8C"),
                Swatch("Muted Berry", "#9C5468"),
                Swatch("Rosy Mauve", "#B27080"),
                Swatch("Cool Pink", "#D98A9E"),
            ),
            blush_shades=(
                Swatch("Soft Pink Blush", "#E0A8B4"),
                Swatch("Mauve Blush", "#C48B96"),
            ),
        ),
        jewelry=JewelryGuidance(
            metal="Silver",
            tip=(
                "Silver, platinum, and white gold complement your cool undertone — "
                "yellow gold can look harsh against your softer coloring."
            ),
        ),
        shopping_guidance=(
            "Build your wardrobe around soft, cool neutrals like dove gray, soft "
            "navy, and rose beige, then bring in muted blues, lavenders, and dusty "
            "rose as accent pieces."
        ),
    ),
    "Autumn": BeautyGuidance(
        makeup=MakeupGuidance(
            foundation_undertone="Warm, golden-olive undertone",
            foundation_tip=(
                "Look for foundations labeled 'warm' or 'golden' — avoid pink or "
                "cool-toned shades, which can wash you out."
            ),
            lip_shades=(
                Swatch("Brick Red", "#A34A38"),
                Swatch("Terracotta Nude", "#B5684A"),
                Swatch("Warm Berry", "#8C3D3A"),
                Swatch("Spiced Coral", "#C15A3E"),
            ),
            blush_shades=(
                Swatch("Terracotta Blush", "#C97654"),
                Swatch("Warm Amber Blush", "#B8703E"),
            ),
        ),
        jewelry=JewelryGuidance(
            metal="Gold",
            tip=(
                "Antique or brushed gold, copper, and bronze metals echo your "
                "warm depth — silver tends to look cold against it."
            ),
        ),
        shopping_guidance=(
            "Anchor your wardrobe in warm neutrals like camel, chocolate, and "
            "olive, then layer in rich rust, mustard, and forest tones for depth."
        ),
    ),
    "Winter": BeautyGuidance(
        makeup=MakeupGuidance(
            foundation_undertone="Cool, rosy-blue undertone",
            foundation_tip=(
                "Look for foundations labeled 'cool' or 'true' — avoid warm "
                "golden or peachy shades, which can clash."
            ),
            lip_shades=(
                Swatch("True Red Lip", "#C41E3A"),
                Swatch("Berry Wine", "#6E1E3A"),
                Swatch("Fuchsia Pink", "#C6127A"),
                Swatch("Blue-Red", "#B31A2E"),
            ),
            blush_shades=(
                Swatch("Cool Pink Blush", "#C97A9C"),
                Swatch("Berry Blush", "#A8506E"),
            ),
        ),
        jewelry=JewelryGuidance(
            metal="Silver",
            tip=(
                "Silver, platinum, and white gold match your cool, clear "
                "coloring — yellow gold can look dull against your natural contrast."
            ),
        ),
        shopping_guidance=(
            "Build around high-contrast neutrals like black, white, and charcoal, "
            "then let jewel tones — emerald, sapphire, true red — do the talking "
            "in your accent pieces."
        ),
    ),
}
