"""Reference swatch data for each color season's free-tier result.

Static, curated color-theory reference data — not derived from a user's
photo and not generated by an LLM (see CLAUDE.md's classifier rule; this
module only maps an already-decided `Season` to a fixed display palette).
The paid tier's full ~20-30 color palette is out of scope for v1's free scan.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.vision.season_classifier import Season


@dataclass(frozen=True)
class Swatch:
    name: str
    hex: str  # "#RRGGBB"


SWATCHES_BY_SEASON: dict[Season, tuple[Swatch, ...]] = {
    "Spring": (
        Swatch("Coral", "#FF7F5E"),
        Swatch("Peach", "#FFB48A"),
        Swatch("Golden Yellow", "#FFCB47"),
        Swatch("Warm Turquoise", "#2FBFA0"),
        Swatch("Grass Green", "#8FCB45"),
    ),
    "Summer": (
        Swatch("Powder Blue", "#A7C4D9"),
        Swatch("Soft Rose", "#D98A99"),
        Swatch("Lavender", "#B6A6CA"),
        Swatch("Dusty Mauve", "#B98EA0"),
        Swatch("Slate Blue-Gray", "#7C93A8"),
    ),
    "Autumn": (
        Swatch("Burnt Orange", "#C1622D"),
        Swatch("Olive Green", "#6B7A3A"),
        Swatch("Mustard Gold", "#C9A227"),
        Swatch("Terracotta", "#B5563A"),
        Swatch("Chocolate Brown", "#6B4226"),
    ),
    "Winter": (
        Swatch("True Red", "#D0103A"),
        Swatch("Emerald Green", "#00693E"),
        Swatch("Sapphire Blue", "#1E3A8A"),
        Swatch("Fuchsia", "#C6127A"),
        Swatch("Icy Blue", "#A9D6E5"),
    ),
}
