"""Reference swatch data for each color season's free and paid results.

Static, curated color-theory reference data — not derived from a user's
photo and not generated by an LLM (see CLAUDE.md's classifier rule; this
module only maps an already-decided `Season` to a fixed display palette).
`SWATCHES_BY_SEASON` is the small free-tier preview; `FULL_PALETTE_BY_SEASON`
is the paid tier's full ~20-30 color palette, organized best/good/avoid.
"""

from __future__ import annotations

from dataclasses import dataclass

from app.vision.season_classifier import Season


@dataclass(frozen=True)
class Swatch:
    name: str
    hex: str  # "#RRGGBB"


SWATCHES_BY_SEASON: dict[Season, tuple[Swatch, ...]] = {
    "Spring": (
        Swatch("Coral", "#FF7F5E"),
        Swatch("Peach", "#FFB48A"),
        Swatch("Golden Yellow", "#FFCB47"),
        Swatch("Warm Turquoise", "#2FBFA0"),
        Swatch("Grass Green", "#8FCB45"),
    ),
    "Summer": (
        Swatch("Powder Blue", "#A7C4D9"),
        Swatch("Soft Rose", "#D98A99"),
        Swatch("Lavender", "#B6A6CA"),
        Swatch("Dusty Mauve", "#B98EA0"),
        Swatch("Slate Blue-Gray", "#7C93A8"),
    ),
    "Autumn": (
        Swatch("Burnt Orange", "#C1622D"),
        Swatch("Olive Green", "#6B7A3A"),
        Swatch("Mustard Gold", "#C9A227"),
        Swatch("Terracotta", "#B5563A"),
        Swatch("Chocolate Brown", "#6B4226"),
    ),
    "Winter": (
        Swatch("True Red", "#D0103A"),
        Swatch("Emerald Green", "#00693E"),
        Swatch("Sapphire Blue", "#1E3A8A"),
        Swatch("Fuchsia", "#C6127A"),
        Swatch("Icy Blue", "#A9D6E5"),
    ),
}


@dataclass(frozen=True)
class SeasonPalette:
    """A paid-tier full color palette for one season, split by how well a
    color suits that season's warm/cool + light/deep + clear/muted profile."""

    best: tuple[Swatch, ...]
    good: tuple[Swatch, ...]
    avoid: tuple[Swatch, ...]


# The paid tier's full ~20-30 color palette per season, organized best/good/avoid.
# `best` is a superset of SWATCHES_BY_SEASON's free-tier colors so the free
# preview never disagrees with the paid tier about what's recommended.
FULL_PALETTE_BY_SEASON: dict[Season, SeasonPalette] = {
    "Spring": SeasonPalette(
        best=(
            Swatch("Coral", "#FF7F5E"),
            Swatch("Peach", "#FFB48A"),
            Swatch("Golden Yellow", "#FFCB47"),
            Swatch("Warm Turquoise", "#2FBFA0"),
            Swatch("Grass Green", "#8FCB45"),
            Swatch("Apricot", "#FFA24B"),
            Swatch("Warm Coral Pink", "#FF9E80"),
            Swatch("Camel", "#C89F6E"),
            Swatch("Bright Warm Blue", "#3D9BE0"),
            Swatch("Ivory", "#FFF3DD"),
            Swatch("Tomato Red", "#E5482B"),
            Swatch("Light Warm Gold", "#E8B04B"),
        ),
        good=(
            Swatch("Buttercup Yellow", "#FDE24F"),
            Swatch("Salmon Pink", "#FF8E72"),
            Swatch("Aqua Green", "#4FCB9E"),
            Swatch("Warm Beige", "#E7C9A0"),
            Swatch("Light Moss Green", "#A3C36B"),
            Swatch("Warm Periwinkle", "#6E9BD4"),
            Swatch("Soft Tangerine", "#FFA65C"),
            Swatch("Warm Khaki", "#D8C58A"),
            Swatch("Light Coral Rose", "#F79D8A"),
        ),
        avoid=(
            Swatch("Black", "#1A1A1A"),
            Swatch("Charcoal Gray", "#4A4A4A"),
            Swatch("Icy Pastel Blue", "#CDE7F0"),
            Swatch("Burgundy", "#5C1A2E"),
            Swatch("Plum", "#5B3256"),
            Swatch("Cool Fuchsia", "#A0116D"),
            Swatch("Navy Blue", "#16264D"),
        ),
    ),
    "Summer": SeasonPalette(
        best=(
            Swatch("Powder Blue", "#A7C4D9"),
            Swatch("Soft Rose", "#D98A99"),
            Swatch("Lavender", "#B6A6CA"),
            Swatch("Dusty Mauve", "#B98EA0"),
            Swatch("Slate Blue-Gray", "#7C93A8"),
            Swatch("Soft Pink", "#E3B7C4"),
            Swatch("Dusty Teal", "#6FA3A0"),
            Swatch("Cool Gray", "#9CA3AD"),
            Swatch("Rose Brown", "#A9827A"),
            Swatch("Soft Sky Blue", "#A9CBE0"),
            Swatch("Mauve Plum", "#8E6B85"),
            Swatch("Muted Sea Foam", "#9CC2B8"),
        ),
        good=(
            Swatch("Soft Periwinkle", "#8FA0C9"),
            Swatch("Blush Pink", "#E8C4CB"),
            Swatch("Soft Lilac", "#C7B8DA"),
            Swatch("Muted Raspberry", "#B15C72"),
            Swatch("Cool Taupe", "#A79A94"),
            Swatch("Powder Teal", "#8FB8B5"),
            Swatch("Soft Denim Blue", "#6F8FAE"),
            Swatch("Dusty Plum", "#7A5A72"),
            Swatch("Cool Ivory", "#EDEAE3"),
        ),
        avoid=(
            Swatch("Orange", "#E8631C"),
            Swatch("Bright Golden Yellow", "#F5C518"),
            Swatch("Black", "#1A1A1A"),
            Swatch("Warm Rust", "#A54A2A"),
            Swatch("Chocolate Brown", "#5A3A28"),
            Swatch("Warm Tomato Red", "#D9432B"),
            Swatch("Mustard", "#C9A227"),
        ),
    ),
    "Autumn": SeasonPalette(
        best=(
            Swatch("Burnt Orange", "#C1622D"),
            Swatch("Olive Green", "#6B7A3A"),
            Swatch("Mustard Gold", "#C9A227"),
            Swatch("Terracotta", "#B5563A"),
            Swatch("Chocolate Brown", "#6B4226"),
            Swatch("Rust", "#A0522D"),
            Swatch("Deep Camel", "#B58B4C"),
            Swatch("Moss Green", "#7A7D3A"),
            Swatch("Pumpkin", "#D2691E"),
            Swatch("Warm Gold", "#C99A3C"),
            Swatch("Brick Red", "#9E3B2E"),
            Swatch("Deep Warm Teal", "#2E6B5E"),
        ),
        good=(
            Swatch("Deep Warm Khaki", "#B8A268"),
            Swatch("Copper", "#B0713A"),
            Swatch("Warm Forest Green", "#4A5D32"),
            Swatch("Deep Peach", "#D98352"),
            Swatch("Warm Sienna", "#8B4A2B"),
            Swatch("Golden Olive", "#9C8A3E"),
            Swatch("Cinnamon", "#9C5A3C"),
            Swatch("Deep Amber", "#C97B2C"),
            Swatch("Muted Tomato", "#B4472F"),
        ),
        avoid=(
            Swatch("Icy Blue", "#CDE7F0"),
            Swatch("Cool Magenta", "#B0189E"),
            Swatch("Black", "#1A1A1A"),
            Swatch("Pure White", "#FFFFFF"),
            Swatch("Cool Lavender", "#A99BC7"),
            Swatch("Icy Pink", "#F2C6D6"),
            Swatch("Cool Navy", "#1B2A4A"),
        ),
    ),
    "Winter": SeasonPalette(
        best=(
            Swatch("True Red", "#D0103A"),
            Swatch("Emerald Green", "#00693E"),
            Swatch("Sapphire Blue", "#1E3A8A"),
            Swatch("Fuchsia", "#C6127A"),
            Swatch("Icy Blue", "#A9D6E5"),
            Swatch("Pure White", "#FFFFFF"),
            Swatch("Black", "#0D0D0D"),
            Swatch("Royal Purple", "#4B1E8C"),
            Swatch("Hot Pink", "#E6136B"),
            Swatch("Cobalt Blue", "#1A5FB4"),
            Swatch("Ice Pink", "#F2C6D6"),
            Swatch("Deep Magenta", "#9C1268"),
        ),
        good=(
            Swatch("Cool Lemon Yellow", "#F5E64C"),
            Swatch("Silver Gray", "#B0B4B8"),
            Swatch("Cool Teal", "#0E8C7F"),
            Swatch("Deep Violet", "#5B2C8C"),
            Swatch("Icy Lilac", "#C9C6E8"),
            Swatch("Charcoal", "#2E2E2E"),
            Swatch("Berry Pink", "#B6206E"),
            Swatch("Cool Sky Blue", "#4FA3D9"),
            Swatch("Platinum", "#D8D8D8"),
        ),
        avoid=(
            Swatch("Orange", "#E8631C"),
            Swatch("Mustard", "#C9A227"),
            Swatch("Rust", "#A0522D"),
            Swatch("Warm Camel", "#C89F6E"),
            Swatch("Olive Green", "#6B7A3A"),
            Swatch("Peach", "#FFB48A"),
            Swatch("Warm Ivory", "#FFF3DD"),
        ),
    ),
}
